#!/bin/bash
# Script para descargar el .exe generado por GitHub Actions

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                  DESCARGAR .EXE DESDE GITHUB ACTIONS                      ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "INSTRUCCIONES:"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. OPCIÓN A: Si tienes el repositorio en GitHub"
echo "   • Ve a: https://github.com/tu-usuario/espapp-env"
echo "   • Haz clic en 'Actions' (pestaña superior)"
echo "   • Selecciona el workflow 'Generar .exe para Windows'"
echo "   • Haz clic en el último build exitoso"
echo "   • Descarga el artefacto 'espapp-windows'"
echo "   • Dentro está: espapp.exe"
echo ""
echo "2. OPCIÓN B: Ejecutar manualmente"
echo "   • Ve a Actions → Generar .exe para Windows"
echo "   • Haz clic en 'Run workflow' (botón derecho)"
echo "   • Espera a que termine (2-3 minutos)"
echo "   • Descarga los artefactos"
echo ""
echo "3. OPCIÓN C: Con cada push automáticamente"
echo "   • El workflow se ejecuta automáticamente cada vez que hagas push"
echo "   • Ve a Actions para descargar los artefactos"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📦 ARCHIVOS GENERADOS:"
echo ""
echo "✓ espapp-windows/"
echo "  • espapp.exe (150-200MB)"
echo "  • windows_installer/ (scripts NSIS)"
echo ""
echo "✓ espapp-linux/"
echo "  • paquetes/espapp_1.0_*.deb"
echo "  • dist/espapp (ejecutable Linux)"
echo ""
echo "✓ espapp-macos/"
echo "  • dist/espapp (ejecutable macOS)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔗 ENLACES RÁPIDOS:"
echo ""
echo "GitHub Actions: https://github.com/YOUR-USERNAME/espapp-env/actions"
echo "Releases: https://github.com/YOUR-USERNAME/espapp-env/releases"
echo ""
